dist: trusty
sudo: required
language: c
compiler:
  - clang
  - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpopt-dev libgeoip-dev

script: CFLAGS="-O2 -g -Werror" LIBS=-lrt USE_GEOIP=no LIBPATH=/usr/lib/x86_64-linux-gnu make && make check

